/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/action': RouteRecordInfo<'/action', '/action', Record<never, never>, Record<never, never>>,
    '/camera': RouteRecordInfo<'/camera', '/camera', Record<never, never>, Record<never, never>>,
    '/recognition': RouteRecordInfo<'/recognition', '/recognition', Record<never, never>, Record<never, never>>,
    '/test/debug': RouteRecordInfo<'/test/debug', '/test/debug', Record<never, never>, Record<never, never>>,
    '/test/webrtc': RouteRecordInfo<'/test/webrtc', '/test/webrtc', Record<never, never>, Record<never, never>>,
  }
}
